---
title: "Ben Woodruff's Resume"
author: Ben Woodruff
date: "`r Sys.Date()`"
knit: pagedown::chrome_print
output:
  pagedown::html_resume:
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: true
    css: ["resume_woodruff.css", "resume"]
---


Aside
================================================================================

Contact Info {#contact}
--------------------------------------------------------------------------------

- <i class="fa fa-envelope"></i> bmwoodruff@gmail.com
- <i class="fa fa-globe"></i> [byuimath.com/bmw/all/pw/](https://byuimath.com/bmw/all/pw)
- <i class="fa fa-github"></i> [github.com/bmwoodruff](https://github.com/bmwoodruff)
<!---
- <i class="fa fa-linkedin"></i> [linkedin.com/in/ben-woodruff-4523485/](https://www.linkedin.com/in/ben-woodruff-4523485/)
- <i class="fa fa-phone"></i> +1 208-227-4984
--->


Skills {#skills}
--------------------------------------------------------------------------------

- Highly skilled in LaTeX (20+ years), R (8+ years), Mathematica (10+ years), and Linux (20+ years). Capable and familiar with many other languages including HTML/CSS, JavaScript, SQL, C++, Python, and more.

- Data visualization instruction using [tidyverse](https://ggplot2.tidyverse.org/).

- Mathematics, Data Science and Statistics teaching and course development.

- Author and coauthor for 10+ [open source education texts/problem sets](https://byuimath.com/bmw/all/pw/index.php?n=Main.EducationMaterials) for mathematics, statistics, and data science. 

Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Made with [**pagedown**](https://github.com/rstudio/pagedown).   
Last updated on `r Sys.Date()`.   



Main
================================================================================

[Ben Woodruff](https://byuimath.com/bmw/all/pw/) {#title}
--------------------------------------------------------------------------------



Work Experience {data-icon=laptop}
--------------------------------------------------------------------------------

### Professor of Mathematics

Brigham Young University -- Idaho 

Rexburg, ID

2005 - Current


- Teach undergraduate mathematics, data science, and statistics courses such as multivariate calculus, data wrangling and visualization, abstract algebra, introduction to analysis, linear algebra (intro and senior level), differential equations (ordinary and partial), engineering statistics, etc.
- (2021+) Collaborated to create an R (tidyerse) data wrangling and visualization text, serving 200+ students a year and growing.
- (2019+) Collaborated to create *Applied Calculus for Data Analysis*, a calculus course focusing on data science applications, wrote over 1/3 of the course text, and wrote and maintain all course related R Shiny apps.
- (2013+) Department webmaster, serving a variety of courses impacting over 30 instructors and 5000 students every semester, including setup and maintenance for open source PHP wikis and SQL databases. 
- (2014+) Created and maintain a JavaScript [normal probability applet](https://byuimath.com/apps/normprob.html) used by statistics courses at BYU-I and BYU Pathway World wide, serving 2500+ students a year around the globe.
- (2015-18) Used R to automate course package creation for all on campus statistics courses, saving faculty 1000+ hours.
- (2009+) Created and maintain PmWiki's open source  [jsMath](https://www.pmwiki.org/wiki/Cookbook/jsMath) and [SageCell](https://www.pmwiki.org/wiki/Cookbook/SageCell) cookbooks.
- (2005 - current) Create open source textbooks, problem sets, and more. See  [byuimath.com/bmw/all/pw](https://byuimath.com/bmw/all/pw/).
- (2012+) Department internship coordinator: mentor 10-30 majors/year.
- (2021+) Mastery Learning Practitioner Coordinator and Thinkshop Lead


### Mathematical Association of America Service 

Intermountain Section of the MAA

[maa.org](https://www.maa.org/)

2002 - current

- Intermountain Section Teaching Award (2016)
- Contributed talks organizer (2012-14) - coordinate 50+ conference talks
- Elected First Vice Chair (2015-16) - section leadership
- Webmaster and technical support (2016-22) - section leadership
- Conference organizer for yearly meeting (2021) with 150+ participants 

Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------


### Brigham Young University

Ph.D. in Mathematics (summa cum laude)

Provo, Utah

2005

Dissertation: [Statistical Properties of Thompson's Group and Random Pseudo Manifolds](https://scholarsarchive.byu.edu/etd/568/)

### Utah State University

B.S. in Mathematics (summa cum laude)

Logan, Utah

2001
